2025-07-05 22:53:32 - INFO - uvicorn.error - Started server process [49869]
2025-07-05 22:53:32 - INFO - uvicorn.error - Waiting for application startup.
2025-07-05 22:53:32 - INFO - uvicorn.error - Application startup complete.
2025-07-05 22:53:32 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-05 23:04:54 - INFO - uvicorn.error - Shutting down
2025-07-05 23:04:54 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-05 23:04:54 - INFO - uvicorn.error - Application shutdown complete.
2025-07-05 23:04:54 - INFO - uvicorn.error - Finished server process [49869]
2025-07-05 23:04:57 - INFO - uvicorn.error - Started server process [58581]
2025-07-05 23:04:57 - INFO - uvicorn.error - Waiting for application startup.
2025-07-05 23:04:57 - INFO - uvicorn.error - Application startup complete.
2025-07-05 23:04:57 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-05 23:05:25 - INFO - uvicorn.error - Shutting down
2025-07-05 23:05:25 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-05 23:05:25 - INFO - uvicorn.error - Application shutdown complete.
2025-07-05 23:05:25 - INFO - uvicorn.error - Finished server process [58581]
2025-07-05 23:05:34 - INFO - uvicorn.error - Started server process [59183]
2025-07-05 23:05:34 - INFO - uvicorn.error - Waiting for application startup.
2025-07-05 23:05:34 - INFO - uvicorn.error - Application startup complete.
2025-07-05 23:05:34 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-05 23:07:44 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Платежи' для workspace 0
2025-07-05 23:07:44 - WARNING - app.routers.dds_articles - Ошибка доступа при создании статьи ДДС: Недостаточно прав для этого рабочего пространства.
2025-07-05 23:07:51 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Платежи' для workspace 0
2025-07-05 23:07:51 - WARNING - app.routers.dds_articles - Ошибка доступа при создании статьи ДДС: Недостаточно прав для этого рабочего пространства.
2025-07-05 23:07:59 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Платежи' для workspace 0
2025-07-05 23:07:59 - WARNING - app.routers.dds_articles - Ошибка доступа при создании статьи ДДС: Недостаточно прав для этого рабочего пространства.
2025-07-05 23:08:14 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Платежи' для workspace 0
2025-07-05 23:08:14 - WARNING - app.routers.dds_articles - Ошибка доступа при создании статьи ДДС: Недостаточно прав для этого рабочего пространства.
2025-07-05 23:08:30 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Платежи' для workspace 43
2025-07-05 23:08:30 - ERROR - app.routers.dds_articles - Непредвиденная ошибка при создании статьи ДДС: (psycopg2.errors.ForeignKeyViolation) insert or update on table "dds_articles" violates foreign key constraint "fk_dds_articles_parent"
DETAIL:  Key (parent_id)=(0) is not present in table "dds_articles".

[SQL: INSERT INTO dds_articles (name, article_type, parent_id, is_active, workspace_id) VALUES (%(name)s, %(article_type)s, %(parent_id)s, %(is_active)s, %(workspace_id)s) RETURNING dds_articles.id, dds_articles.created_at, dds_articles.updated_at]
[parameters: {'name': 'Платежи', 'article_type': 'expense', 'parent_id': 0, 'is_active': True, 'workspace_id': 43}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "dds_articles" violates foreign key constraint "fk_dds_articles_parent"
DETAIL:  Key (parent_id)=(0) is not present in table "dds_articles".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/dds_articles.py", line 50, in create_dds_article
    article = dds_article_service.create_article(
  File "/home/true/Projects/money_flow_app/backend/app/services/dds_article_service.py", line 53, in create_article
    db_article = crud.dds_article.create_with_owner(
  File "/home/true/Projects/money_flow_app/backend/app/crud/crud_dds_article.py", line 76, in create_with_owner
    db.commit()
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4477, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/true/Projects/money_flow_app/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "dds_articles" violates foreign key constraint "fk_dds_articles_parent"
DETAIL:  Key (parent_id)=(0) is not present in table "dds_articles".

[SQL: INSERT INTO dds_articles (name, article_type, parent_id, is_active, workspace_id) VALUES (%(name)s, %(article_type)s, %(parent_id)s, %(is_active)s, %(workspace_id)s) RETURNING dds_articles.id, dds_articles.created_at, dds_articles.updated_at]
[parameters: {'name': 'Платежи', 'article_type': 'expense', 'parent_id': 0, 'is_active': True, 'workspace_id': 43}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-06 12:04:19 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Выручка от продаж' для workspace 1
2025-07-06 12:04:19 - WARNING - app.routers.dds_articles - Ошибка доступа при создании статьи ДДС: Недостаточно прав для этого рабочего пространства.
2025-07-06 12:04:26 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Выручка от продаж' для workspace 43
2025-07-06 12:04:26 - INFO - app.routers.dds_articles - Статья ДДС с ID 653 успешно создана.
2025-07-06 12:12:21 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Выручка от продаж товаров' для workspace 43
2025-07-06 12:12:22 - INFO - app.routers.dds_articles - Статья ДДС с ID 654 успешно создана.
2025-07-06 12:12:40 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Выручка от продаж товаров' для workspace 43
2025-07-06 12:12:40 - WARNING - app.routers.dds_articles - Попытка создания дубликата статьи ДДС: Статья с именем 'Выручка от продаж товаров' уже существует.
2025-07-06 12:12:58 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'Выручка от продаж товаров 1 категории' для workspace 43
2025-07-06 12:12:58 - INFO - app.routers.dds_articles - Статья ДДС с ID 655 успешно создана.
2025-07-06 12:56:28 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'фыв' для workspace 43
2025-07-06 12:56:28 - INFO - app.routers.dds_articles - Статья ДДС с ID 656 успешно создана.
2025-07-06 12:56:37 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'пар' для workspace 43
2025-07-06 12:56:37 - INFO - app.routers.dds_articles - Статья ДДС с ID 657 успешно создана.
2025-07-06 13:03:02 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'пыва' для workspace 43
2025-07-06 13:03:02 - INFO - app.routers.dds_articles - Статья ДДС с ID 658 успешно создана.
2025-07-06 13:14:00 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'фыв' для workspace 43
2025-07-06 13:14:00 - WARNING - app.routers.dds_articles - Попытка создания дубликата статьи ДДС: Статья с именем 'фыв' уже существует.
2025-07-06 13:18:44 - INFO - app.routers.dds_articles - Попытка создания статьи ДДС 'description' для workspace 43
2025-07-06 13:18:44 - INFO - app.routers.dds_articles - Статья ДДС с ID 659 успешно создана.
2025-07-06 16:59:35 - INFO - uvicorn.error - Started server process [6405]
2025-07-06 16:59:35 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 16:59:35 - INFO - uvicorn.error - Application startup complete.
2025-07-06 16:59:35 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 21:23:33 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:23:33 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:23:38 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:23:38 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:24:30 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:24:30 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:25:29 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:25:29 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:25 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:25 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:34 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:34 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:43 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:43 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:43 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:43 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:43 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:43 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:44 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:44 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:47 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:47 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:27:58 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:27:58 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    if workspace_id not in [ws.id for ws in current_user.workspaces]:
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:32:18 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:32:18 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:32:30 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:32:30 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:35:01 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:35:01 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:37:25 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:37:25 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:37:26 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:37:26 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:37:30 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:37:30 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:38:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:38:44 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    # 2. Проверяем права на счета и их существование
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:38:50 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:38:50 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    if transaction_in.from_account_id:
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 21:42:43 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:42:43 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    if transaction_in.account_id:
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 21:42:48 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:42:48 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    if transaction_in.account_id:
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 21:44:17 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 49 пользователем admin1434311@admin.ru
2025-07-06 21:44:17 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 49: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 21:50:35 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 50 пользователем admin114341@admin.ru
2025-07-06 21:50:35 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 50: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:50:42 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 50 пользователем admin114341@admin.ru
2025-07-06 21:50:42 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 50: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:52:46 - INFO - uvicorn.error - Shutting down
2025-07-06 21:52:46 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-06 21:52:46 - INFO - uvicorn.error - Application shutdown complete.
2025-07-06 21:52:46 - INFO - uvicorn.error - Finished server process [6405]
2025-07-06 21:52:49 - INFO - uvicorn.error - Started server process [215243]
2025-07-06 21:52:49 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 21:52:49 - INFO - uvicorn.error - Application startup complete.
2025-07-06 21:52:49 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 21:52:56 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 50 пользователем admin114341@admin.ru
2025-07-06 21:52:56 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 50: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:54:50 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 50 пользователем admin114341@admin.ru
2025-07-06 21:54:50 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 50: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 21:55:04 - INFO - uvicorn.error - Shutting down
2025-07-06 21:55:04 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-06 21:55:04 - INFO - uvicorn.error - Application shutdown complete.
2025-07-06 21:55:04 - INFO - uvicorn.error - Finished server process [215243]
2025-07-06 21:55:08 - INFO - uvicorn.error - Started server process [217365]
2025-07-06 21:55:08 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 21:55:08 - INFO - uvicorn.error - Application startup complete.
2025-07-06 21:55:08 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 21:58:05 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 21:58:05 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:00:07 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:00:07 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:02:09 - INFO - uvicorn.error - Shutting down
2025-07-06 22:02:09 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-06 22:02:09 - INFO - uvicorn.error - Application shutdown complete.
2025-07-06 22:02:09 - INFO - uvicorn.error - Finished server process [217365]
2025-07-06 22:02:14 - INFO - uvicorn.error - Started server process [222782]
2025-07-06 22:02:14 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 22:02:14 - INFO - uvicorn.error - Application startup complete.
2025-07-06 22:02:14 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 22:02:24 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:02:24 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:02:59 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:02:59 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:03:17 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:03:17 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:04:55 - INFO - uvicorn.error - Shutting down
2025-07-06 22:04:55 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-06 22:04:55 - INFO - uvicorn.error - Application shutdown complete.
2025-07-06 22:04:55 - INFO - uvicorn.error - Finished server process [222782]
2025-07-06 22:04:58 - INFO - uvicorn.error - Started server process [225003]
2025-07-06 22:04:58 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 22:04:58 - INFO - uvicorn.error - Application startup complete.
2025-07-06 22:04:58 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 22:05:20 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:05:20 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:13:30 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:13:30 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:15:10 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:15:10 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:17:27 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:17:27 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 51: Для расхода должен быть указан счет-источник.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 51, in create_transaction
    raise ValueError("Для расхода должен быть указан счет-источник.")
ValueError: Для расхода должен быть указан счет-источник.
2025-07-06 22:18:19 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:18:19 - INFO - app.routers.transactions - Транзакция с ID 72 успешно создана для workspace 51.
2025-07-06 22:20:32 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:20:32 - INFO - app.routers.transactions - Транзакция с ID 73 успешно создана для workspace 51.
2025-07-06 22:21:12 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 51 пользователем admin11asdas111@admin.ru
2025-07-06 22:21:12 - INFO - app.routers.transactions - Транзакция с ID 74 успешно создана для workspace 51.
2025-07-06 22:31:17 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:31:17 - INFO - app.routers.transactions - Транзакция с ID 79 успешно создана для workspace 52.
2025-07-06 22:32:28 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:32:28 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 78, in create_transaction
    db=db,
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:34:07 - INFO - uvicorn.error - Shutting down
2025-07-06 22:34:07 - INFO - uvicorn.error - Waiting for application shutdown.
2025-07-06 22:34:07 - INFO - uvicorn.error - Application shutdown complete.
2025-07-06 22:34:07 - INFO - uvicorn.error - Finished server process [225003]
2025-07-06 22:34:34 - INFO - uvicorn.error - Started server process [247184]
2025-07-06 22:34:34 - INFO - uvicorn.error - Waiting for application startup.
2025-07-06 22:34:34 - INFO - uvicorn.error - Application startup complete.
2025-07-06 22:34:34 - INFO - uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
2025-07-06 22:34:35 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:34:35 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:34 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:34 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:40 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:40 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:44 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:44 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:44 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:45 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:45 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:45 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    try:
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:36:49 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:36:49 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:37:03 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:37:03 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:37:15 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:37:15 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:37:18 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:37:18 - ERROR - app.routers.transactions - Непредвиденная ошибка при создании транзакции для workspace 52: Для дохода должен быть указан счет-получатель.
Traceback (most recent call last):
  File "/home/true/Projects/money_flow_app/backend/app/routers/transactions.py", line 77, in create_transaction
    transaction = transaction_service.create_transaction(
  File "/home/true/Projects/money_flow_app/backend/app/services/transaction_service.py", line 53, in create_transaction
    raise ValueError("Для дохода должен быть указан счет-получатель.")
ValueError: Для дохода должен быть указан счет-получатель.
2025-07-06 22:38:20 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:38:20 - INFO - app.routers.transactions - Транзакция с ID 80 успешно создана для workspace 52.
2025-07-06 22:38:35 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:38:35 - INFO - app.routers.transactions - Транзакция с ID 81 успешно создана для workspace 52.
2025-07-06 22:48:06 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:48:06 - INFO - app.routers.transactions - Транзакция с ID 82 успешно создана для workspace 52.
2025-07-06 22:54:24 - INFO - app.routers.transactions - Попытка создания транзакции для workspace 52 пользователем admin13451@admin.ru
2025-07-06 22:54:24 - INFO - app.routers.transactions - Транзакция с ID 83 успешно создана для workspace 52.
